Add profile page
ourzora/nouns-builder pull request #249
Opened 2023-05-15 07:26 UTC by neokry

## Description

Adds profile pages for users

## Motivation & context

- users want to show off dao membership
- users want to see what daos other users are in

## Code review

- does profile page correctly show all DAO tokens for a user
- does layout work properly on desktop and mobile
- activity page was refactored to share pagination logic, did this break anything?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

2023-05-22 06:53 UTC, isaaczaak requested changes
Add maxwidth to profile page so it lines up with universal navbar

2023-05-22 06:54 UTC, isaaczaak commented
Follow-up PR:

Rearrange dropdown component so that this section is at the top, just underneath `Profile` and `Create a DAO` CTAs.
<img width="249" alt="Screenshot 2023-05-22 at 4 53 53 pm" src="https://github.com/ourzora/nouns-builder/assets/108648359/fbff59b4-f2c7-4bc9-b850-665543beb049">

2023-05-22 08:35 UTC, nadiakiamilev commented on apps/web/src/data/graphql/requests/tokensQuery.ts
> +    name?: string
i believe you can get the typed response from the generated sdk file

2023-05-22 08:37 UTC, nadiakiamilev commented on apps/web/src/pages/api/profile/[user]/tokens.tsx
> +  console.log('user', user)
nit: console statement

2023-05-22 08:38 UTC, nadiakiamilev commented on apps/web/src/pages/api/profile/[user]/tokens.tsx
> +export interface UserTokensResponse {
it looks like this file is a tsx file even thought it's an api route. is that intended? I also noticed `api/profile/[user]/daos` is the same.

2023-05-22 08:39 UTC, nadiakiamilev commented on apps/web/src/pages/api/profile/[user]/tokens.tsx
> +  res.status(200).json({ tokens, daos } as UserTokensResponse)
do we also need to handle some error cases? ie not found?

2023-05-22 08:41 UTC, nadiakiamilev commented on apps/web/src/pages/profile/[user].tsx
> +        mt={isMobile ? 'x14' : undefined}
nit: would prefer the built-in breakpoints here instead of isMobile

2023-05-23 01:38 UTC, neokry commented
thanks for the review @nadiakiamilev just pushed a few commits that should resolve these issues you mentioned.

2023-05-24 05:24 UTC, isaaczaak approved these changes
tested

2023-05-24 08:26 UTC, nadiakiamilev approved these changes

2023-05-24 10:06 UTC, merged